### ISSUE TITLE
Issue while running smpl_relations.py file

### ISSUE THREAD

**Issue by anas-zafar** [gulvarol/surreal#58]
I am facing this error: 
```
mdtype, byte_count = self._matrix_reader.read_full_tag()
  File "mio5_utils.pyx", line 546, in scipy.io.matlab.mio5_utils.VarReader5.read_full_tag
  File "mio5_utils.pyx", line 554, in scipy.io.matlab.mio5_utils.VarReader5.cread_full_tag
  File "streams.pyx", line 150, in scipy.io.matlab.streams.ZlibInputStream.read_into
  File "streams.pyx", line 137, in scipy.io.matlab.streams.ZlibInputStream._fill_buffer
zlib.error: Error -3 while decompressing data: invalid distance too far back
```

while I am trying to run the smpl_relations.py file. Any solution for this problem?

**Comment by anas-zafar** [comment]
@gulvarol the error seems to be occurring when I am trying to load the .mat file
```
import numpy as np
from scipy.io import loadmat

if __name__ == '__main__':
    print('Inside Main')
    mat = loadmat("/content/01_01_c0001_info.mat")
```
The Complete Error is given below:
  ```
  error                                     Traceback (most recent call last)
<ipython-input-4-c3171c29e3cc> in <module>()
      1 if __name__ == '__main__':
      2     print('Inside Main')
----> 3     mat = loadmat("/content/01_01_c0001_info.mat")
      4     print("File Read........")

2 frames
/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio5.py in read_var_header(self)
    224             self._matrix_reader.set_stream(stream)
    225             check_stream_limit = self.verify_compressed_data_integrity
--> 226             mdtype, byte_count = self._matrix_reader.read_full_tag()
    227         else:
    228             check_stream_limit = False

mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.read_full_tag()

mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.cread_full_tag()

streams.pyx in scipy.io.matlab.streams.ZlibInputStream.read_into()

streams.pyx in scipy.io.matlab.streams.ZlibInputStream._fill_buffer()

error: Error -3 while decompressing data: invalid distance too far back
```

**Comment by anas-zafar** [comment]
Data Set got corrupt while downloading. It is fixed now thank you.
